[workspace]

members = [
    "distributed_challenges_solution",
    "node_driver",
    "distributed_challenges",
]

[workspace.dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
