[package]
name = "distributed_challenges"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
node_driver = { path = "../node_driver" }
serde = { workspace = true }
uuid = { version = "1.3.1", features = ["v4"] }
